networks:
  shared-network:
    external: true
services:
  frontend:
    # contextを設定しないとDockerfileのディレクトリを認識できないので、設定する
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend-api"
    ports:
      - 8080:80
    networks:
      - shared-network
  backend:
    # contextを設定しないとDockerfileのディレクトリを認識できないので、設定する
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "backend-api"
    ports:
      - 8000:8000
    networks:
      - shared-network